apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dotnet-ingress
  namespace: api
spec:
  rules:
  - host: training.devops4all.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dotnet-app
            port:
              number: 80
  ingressClassName: nginx